a = float(input("nhap a :"))
b = float(input("nhap b :"))
print("{0}+{1}={2}".format(a,b,a+b))
print("{0}-{1}={2}".format(a,b,a-b))
print("{0}*{1}={2}".format(a,b,a*b))
print("{0}/{1}={2}".format(a,b,a/b))
print("{0}%{1}={2}".format(a,b,a%b))
print("{0}**{1}={2}".format(a,b,a**b))#mũ
print("{0}//{1}={2}".format(a,b,a//b))#chia lấy số nguyên